# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import history_pb2 as history__pb2


class HistoryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getHistory = channel.unary_stream(
        '/history.History/getHistory',
        request_serializer=history__pb2.HistoryRequest.SerializeToString,
        response_deserializer=history__pb2.HistoryRespond.FromString,
        )


class HistoryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getHistory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HistoryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getHistory': grpc.unary_stream_rpc_method_handler(
          servicer.getHistory,
          request_deserializer=history__pb2.HistoryRequest.FromString,
          response_serializer=history__pb2.HistoryRespond.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'history.History', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
