# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messenger_pb2 as messenger__pb2


class MessengerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendMessage = channel.unary_unary(
        '/mesenger.MessengerService/SendMessage',
        request_serializer=messenger__pb2.SendMessageRequest.SerializeToString,
        response_deserializer=messenger__pb2.SendMessageRespond.FromString,
        )
    self.ReceiveMessage = channel.unary_stream(
        '/mesenger.MessengerService/ReceiveMessage',
        request_serializer=messenger__pb2.ReceiveRequest.SerializeToString,
        response_deserializer=messenger__pb2.ReceiveRespond.FromString,
        )


class MessengerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReceiveMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessengerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=messenger__pb2.SendMessageRequest.FromString,
          response_serializer=messenger__pb2.SendMessageRespond.SerializeToString,
      ),
      'ReceiveMessage': grpc.unary_stream_rpc_method_handler(
          servicer.ReceiveMessage,
          request_deserializer=messenger__pb2.ReceiveRequest.FromString,
          response_serializer=messenger__pb2.ReceiveRespond.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mesenger.MessengerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
