# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='mesenger',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fmessenger.proto\x12\x08mesenger\"\x10\n\x0eReceiveRequest\"\x14\n\x12SendMessageRespond\"7\n\x12SendMessageRequest\x12\x10\n\x08receiver\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"1\n\x0eReceiveRespond\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\xa9\x01\n\x10MessengerService\x12K\n\x0bSendMessage\x12\x1c.mesenger.SendMessageRequest\x1a\x1c.mesenger.SendMessageRespond\"\x00\x12H\n\x0eReceiveMessage\x12\x18.mesenger.ReceiveRequest\x1a\x18.mesenger.ReceiveRespond\"\x00\x30\x01\x62\x06proto3'
)




_RECEIVEREQUEST = _descriptor.Descriptor(
  name='ReceiveRequest',
  full_name='mesenger.ReceiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=45,
)


_SENDMESSAGERESPOND = _descriptor.Descriptor(
  name='SendMessageRespond',
  full_name='mesenger.SendMessageRespond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=67,
)


_SENDMESSAGEREQUEST = _descriptor.Descriptor(
  name='SendMessageRequest',
  full_name='mesenger.SendMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='receiver', full_name='mesenger.SendMessageRequest.receiver', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='mesenger.SendMessageRequest.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=124,
)


_RECEIVERESPOND = _descriptor.Descriptor(
  name='ReceiveRespond',
  full_name='mesenger.ReceiveRespond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='mesenger.ReceiveRespond.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='mesenger.ReceiveRespond.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['ReceiveRequest'] = _RECEIVEREQUEST
DESCRIPTOR.message_types_by_name['SendMessageRespond'] = _SENDMESSAGERESPOND
DESCRIPTOR.message_types_by_name['SendMessageRequest'] = _SENDMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['ReceiveRespond'] = _RECEIVERESPOND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReceiveRequest = _reflection.GeneratedProtocolMessageType('ReceiveRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECEIVEREQUEST,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:mesenger.ReceiveRequest)
  })
_sym_db.RegisterMessage(ReceiveRequest)

SendMessageRespond = _reflection.GeneratedProtocolMessageType('SendMessageRespond', (_message.Message,), {
  'DESCRIPTOR' : _SENDMESSAGERESPOND,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:mesenger.SendMessageRespond)
  })
_sym_db.RegisterMessage(SendMessageRespond)

SendMessageRequest = _reflection.GeneratedProtocolMessageType('SendMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDMESSAGEREQUEST,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:mesenger.SendMessageRequest)
  })
_sym_db.RegisterMessage(SendMessageRequest)

ReceiveRespond = _reflection.GeneratedProtocolMessageType('ReceiveRespond', (_message.Message,), {
  'DESCRIPTOR' : _RECEIVERESPOND,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:mesenger.ReceiveRespond)
  })
_sym_db.RegisterMessage(ReceiveRespond)



_MESSENGERSERVICE = _descriptor.ServiceDescriptor(
  name='MessengerService',
  full_name='mesenger.MessengerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=178,
  serialized_end=347,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='mesenger.MessengerService.SendMessage',
    index=0,
    containing_service=None,
    input_type=_SENDMESSAGEREQUEST,
    output_type=_SENDMESSAGERESPOND,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveMessage',
    full_name='mesenger.MessengerService.ReceiveMessage',
    index=1,
    containing_service=None,
    input_type=_RECEIVEREQUEST,
    output_type=_RECEIVERESPOND,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGERSERVICE)

DESCRIPTOR.services_by_name['MessengerService'] = _MESSENGERSERVICE

# @@protoc_insertion_point(module_scope)
