# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gate_control_pb2 as proto_dot_gate__control__pb2


class GateServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Go = channel.unary_unary(
        '/gate_control.GateService/Go',
        request_serializer=proto_dot_gate__control__pb2.GoRequest.SerializeToString,
        response_deserializer=proto_dot_gate__control__pb2.GoRespond.FromString,
        )


class GateServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Go(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GateServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Go': grpc.unary_unary_rpc_method_handler(
          servicer.Go,
          request_deserializer=proto_dot_gate__control__pb2.GoRequest.FromString,
          response_serializer=proto_dot_gate__control__pb2.GoRespond.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gate_control.GateService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
